name: Download App Store Reviews

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  reviews:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python appstore.py

      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: appstore-reviews
          path: reviews.json
